# Event properties
title: LauzHack
date: "November 24-25"
year: 2018
location: EPFL, Switzerland
description: Student-run hackathon at EPFL, Switzerland

# Website config
url: https://lauzhack.com

# Social networks
twitter: lauzhack
facebook: lauzhack
