includes_dir: .

# Compression parameters for the compress.html layout from https://jch.penibelst.de
compress_html:
  clippings: all
  startings: [head, body]
  endings: all

plugins:
  - jekyll-redirect-from
